structure(list(method = "POST", url = "graphql", status_code = 200L, 
    headers = structure(list(`access-control-allow-origin` = "*", 
        `access-control-expose-headers` = "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset, Warning", 
        `content-security-policy` = "default-src 'none'", `content-type` = "application/json; charset=utf-8", 
        date = "Thu, 10 Sep 2026 08:28:40 GMT", `referrer-policy` = "origin-when-cross-origin, strict-origin-when-cross-origin", 
        `strict-transport-security` = "max-age=31536000; includeSubdomains; preload", 
        vary = "Accept-Encoding, Accept, X-Requested-With", `x-accepted-oauth-scopes` = "repo", 
        `x-content-type-options` = "nosniff", `x-frame-options` = "deny", 
        `x-github-media-type` = "github.v3; format=json", `x-oauth-scopes` = "notifications, read:org, read:project, read:repo_hook, repo, user, workflow", 
        `x-ratelimit-limit` = "5000", `x-ratelimit-remaining` = "4945", 
        `x-ratelimit-reset` = "1789031317", `x-ratelimit-resource` = "graphql", 
        `x-ratelimit-used` = "55", `x-xss-protection` = "0", 
        server = "github.com", `x-github-request-id` = "93CC:10BE8F:6F2C00B:6C3401B:6AA26A37", 
        `x-github-edge-region` = "fra"), class = "httr2_headers"), 
    body = charToRaw("{\"data\":{\"repository\":{\"createdAt\":\"2017-06-10T03:38:22Z\",\"issues\":{\"pageInfo\":{\"hasNextPage\":true,\"endCursor\":\"Y3Vyc29yOnYyOpK0MjAxNy0wNi0yMlQwNjo1NTowOFrODivA_A==\"},\"nodes\":[{\"number\":1,\"createdAt\":\"2017-06-10T23:47:38Z\",\"author\":{\"login\":\"mdsumner\"},\"comments\":{\"totalCount\":1}},{\"number\":2,\"createdAt\":\"2017-06-11T01:56:18Z\",\"author\":{\"login\":\"mdsumner\"},\"comments\":{\"totalCount\":10}},{\"number\":3,\"createdAt\":\"2017-06-19T13:48:31Z\",\"author\":{\"login\":\"mdsumner\"},\"comments\":{\"totalCount\":2}},{\"number\":4,\"createdAt\":\"2017-06-22T03:12:21Z\",\"author\":{\"login\":\"mdsumner\"},\"comments\":{\"totalCount\":1}},{\"number\":5,\"createdAt\":\"2017-06-22T06:55:08Z\",\"author\":{\"login\":\"mdsumner\"},\"comments\":{\"totalCount\":2}}]}}}}"), 
    timing = c(redirect = 0, namelookup = 0, connect = 0, pretransfer = 0.000134, 
    starttransfer = 0.423261, total = 0.423307), cache = new.env(parent = emptyenv())), class = "httr2_response")
