structure(list(method = "GET", url = "this-package-does-not-exist-xyz123/json", 
    status_code = 404L, headers = structure(list(`referrer-policy` = "origin-when-cross-origin", 
        `access-control-expose-headers` = "X-PyPI-Last-Serial", 
        `access-control-allow-origin` = "*", `access-control-allow-methods` = "GET", 
        `access-control-max-age` = "86400", `access-control-allow-headers` = "Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since", 
        `content-type` = "application/json", server = "gunicorn", 
        `content-security-policy` = "base-uri 'self'; connect-src 'self' https://api.github.com/repos/ https://api.github.com/search/issues https://gitlab.com/api/ https://analytics.python.org *.ethicalads.io https://api.pwnedpasswords.com https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/sre/mathmaps/ https://2p66nmmycsj3.statuspage.io; default-src 'none'; font-src 'self'; form-action 'self' https://checkout.stripe.com https://billing.stripe.com; frame-ancestors 'none'; frame-src https://www.youtube-nocookie.com; img-src 'self' https://pypi-camo.freetls.fastly.net/ *.ethicalads.io ethicalads.blob.core.windows.net; script-src 'self' https://analytics.python.org *.ethicalads.io 'sha256-U3hKDidudIaxBDEzwGJApJgPEf2mWk6cfMWghrAa6i0=' https://cdn.jsdelivr.net/npm/mathjax@3.2.2/ 'sha256-1CldwzdEg2k1wTmf7s5RWVd7NMXI/7nxxjJM2C4DqII=' https://www.youtube.com https://s.ytimg.com; style-src 'self' *.ethicalads.io 'sha256-2YHqZokjiizkHi1Zt+6ar0XJ0OeEy/egBnlm+MDMtrM=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-JLEjeN9e5dGsz5475WyRaoA4eQOdNPxDIeUhclnJDCE=' 'sha256-mQyxHEuwZJqpxCw3SLmc4YOySNKXunyu2Oiz1r3/wAE=' 'sha256-OCf+kv5Asiwp++8PIevKBYSgnNLNUZvxAp4a7wMLuKA=' 'sha256-h5LOiLhk6wiJrGsG5ItM0KimwzWQH/yAcmoJDJL//bY='", 
        `accept-ranges` = "bytes", date = "Wed, 09 Sep 2026 16:04:06 GMT", 
        `x-served-by` = "cache-iad-kiad7000173-IAD, cache-iad-kiad7000173-IAD, cache-iad-kiad7000132-IAD, cache-fra-eddf8230123-FRA", 
        `x-cache` = "MISS, MISS, MISS", `x-cache-hits` = "0, 0, 0", 
        `x-timer` = "S1788969846.140878,VS0,VE158", vary = "Accept-Encoding", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        `x-frame-options` = "deny", `x-xss-protection` = "1; mode=block", 
        `x-content-type-options` = "nosniff", `x-permitted-cross-domain-policies` = "none", 
        `permissions-policy` = "publickey-credentials-create=(self),publickey-credentials-get=(self),accelerometer=(),ambient-light-sensor=(),autoplay=(),battery=(),camera=(),display-capture=(),document-domain=(),encrypted-media=(),execution-while-not-rendered=(),execution-while-out-of-viewport=(),fullscreen=(),gamepad=(),geolocation=(),gyroscope=(),hid=(),identity-credentials-get=(),idle-detection=(),local-fonts=(),magnetometer=(),microphone=(),midi=(),otp-credentials=(),payment=(),picture-in-picture=(),screen-wake-lock=(),serial=(),speaker-selection=(),storage-access=(),usb=(),web-share=(),xr-spatial-tracking=()", 
        `content-length` = "24"), class = "httr2_headers"), body = charToRaw("{\"message\": \"Not Found\"}"), 
    timing = c(redirect = 0, namelookup = 0, connect = 0, pretransfer = 0.000128, 
    starttransfer = 0.282312, total = 0.282548), cache = new.env(parent = emptyenv())), class = "httr2_response")
